### ISSUE TITLE
ENV UNUSED cannot be configured from module

### ISSUE THREAD

**Issue by jayhding** [trussworks/terraform-aws-lambda-amiclean#9]
The `env_vars` setting at https://github.com/trussworks/terraform-aws-lambda-amiclean/blob/master/main.tf#L113 cannot configure all environment variables set in https://github.com/trussworks/truss-aws-tools/tree/master/cmd/ami-cleaner.

The most important missing env is `UNUSED` as described in https://github.com/trussworks/truss-aws-tools/blob/master/cmd/ami-cleaner/main.go#L25. Without passing `--unused` the AMIs in-use would also be deleted, which in my view is not usually people want.

**Comment by rpdelaney** [comment]
Thank you for the report! We have added it to our backlog to address this.
